<?php

/* DATABASE CONSTANTS */

	define("DB_HOST", "bitsycam.com");
	define("DB_NAME", "combustion");
	define("DB_USER", "combustion");
	define("DB_PASS", "combustion");
/*}else{
	//LIVE
	define("DB_HOST", "db626991984.db.1and1.com");
	define("DB_NAME", "db626991984");
	define("DB_USER", "dbo626991984");
	define("DB_PASS", "Sbecky617$");
}*/
/* /DATABASE CONSTANTS */

define("LOGIN_PATH", $_SERVER['DOCUMENT_ROOT'] . "/combustion/includes/php-login-minimal-1.0/");
?>
